# Generated by Django 5.2 on 2025-04-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0002_chatgroup_users_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='users_online',
        ),
    ]
