# Generated by Django 5.2 on 2025-04-11 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0003_remove_chatgroup_users_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='user_online',
            field=models.ManyToManyField(blank=True, related_name='online_in_grouops', to=settings.AUTH_USER_MODEL),
        ),
    ]
