# Generated by Django 5.2 on 2025-04-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0005_alter_chatgroup_user_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='user_online',
            new_name='users_online',
        ),
    ]
